version: '3'

services:
  node-app:
    container_name: node-fmecg
    build: 
      dockerfile: Dockerfile
      context: ./server-web
    volumes:
      - ./server-web/:/server/
      - /server/node_modules
    depends_on:
      - database
    env_file: ./server-web/.env.docker
    networks:
      - network-fmecg
  
  react-app:
    container_name: react-fmecg
    build: 
      dockerfile: Dockerfile
      context: ./frontend_web
    volumes:
      - ./frontend_web:/web/
      - /web/node_modules
    depends_on:
      - database
    networks:
      - network-fmecg

  bin-login:
    container_name: bin-fmecg
    build: 
      dockerfile: Dockerfile
      context: ./frontend_web/bin
    env_file: ./frontend_web/bin/.env.docker
    volumes:
      - ./frontend_web/bin:/bin_login/
      - /bin_login/node_modules
    depends_on:
      - database
      - node-app
    networks:
      - network-fmecg
  
  proxy:
    container_name: proxy-fmecg
    links:
      - node-app
      - react-app
      - bin-login
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./proxy
    ports:
      - 80:80
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network-fmecg

  database:
    image: mysql:8.0
    container_name: database-fmecg
    restart: unless-stopped
    ports:
      - 3306:3306
    expose:
      - 3306
    env_file: ./server-web/.env.docker
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    networks:
      - network-fmecg

  # phpmyadmin:
  #   container_name: phpadmin_fmecg
  #   image: phpmyadmin:5.2.1-apache
  #   restart: unless-stopped
  #   ports:
  #     - 8080:80
  #   expose:
  #     - 8080
  #   environment:
  #     PMA_HOST: database # host is a name of mysql service in docker compose
  #     PMA_PORT: 3306
  #     PMA_USER: root
  #     PMA_PASSWORD: sparclab
  #     MYSQL_ROOT_PASSWORD: sparclab
  #   volumes:
  #     - ./docker/data/phpadmin:/data/:cached
  #   networks:
  #     - network_fmecg

networks:
  network-fmecg:
    driver: bridge
