
services:
  main-server:
    container_name: main-server
    build: 
      dockerfile: Dockerfile
      context: ./server
    ports:
      - 3000:3000
    depends_on:
      - identity-database
      - main-database
      - chat-database
    env_file: ./server/.env.docker
    volumes:
      - ./server/:/server/
      - /server/node_modules
      - /server/dist
    networks:
      -  fmecg-network

  identity:
    container_name: identity-service
    build: 
      dockerfile: Dockerfile
      context: ./identity_service
    ports:
      - 3003:3003
    volumes:
      - ./identity_service/:/identity/
      - /identity/node_modules
      - /identity/dist
    depends_on:
      - identity-database
    env_file: ./identity_service/.env.docker
    networks:
      - fmecg-network
  
  # ui-web:
  #   container_name: ui-web
  #   build: 
  #     dockerfile: Dockerfile
  #     context: ./ui_web
  #   env_file: ./ui_web/.env.docker
  #   ports:
  #     - 3002:3002
  #   volumes:
  #     - ./ui_web/:/ui_web/
  #     - /ui_web/node_modules
  #     - /ui_web/bin/node_modules
  #     - /ui_web/www
  #   depends_on:
  #     - identity-database
  #     - main-database
  #   networks:
  #     - fmecg-network

  identity-database:
    image: mysql:8.0
    container_name: identity-database
    restart: unless-stopped
    ports:
      - 3306:3306
    env_file: ./identity_service/.env.docker
    volumes:
      - ./docker/data/identity_mysql:/var/lib/mysql
    networks:
      - fmecg-network
  
  main-database:
    image: mysql:8.0
    container_name: main-database
    restart: unless-stopped
    ports:
      - 3307:3306
    env_file: ./server/.env.docker
    volumes:
      - ./docker/data/main_mysql:/var/lib/mysql
    networks:
      - fmecg-network
  
  chat-database:
    image: mongodb/mongodb-community-server:6.0.16-ubi8
    container_name: chat-database
    # ports:
    #   - 27017:27017
    env_file: ./server/.env.docker
    volumes:
      - ./docker/data/mongodb:/data/db
    networks:
      - fmecg-network

networks:
  fmecg-network:
    driver: bridge
