
services:
  identity:
    container_name: identity_service
    build: 
      dockerfile: Dockerfile
      context: ./identity_service
    # profiles: ["backend"]
    volumes:
      - ./identity_service/:/server/
      - /identity/node_modules
    depends_on:
      - database
    env_file: ./identity_service/.env.docker
    networks:
      - network-fmecg
  
  ui-web:
    container_name: ui-web
    build: 
      dockerfile: Dockerfile
      context: ./ui
    # profiles: ["frontend"]
    volumes:
      - ./ui-web/:/ui/
      - /ui-web/node_modules
    depends_on:
      - database
    networks:
      - network-fmecg

  database:
    image: mysql:8.0
    container_name: database-identity
    restart: unless-stopped
    profiles: ["backend"]
    ports:
      - 3306:3306
    expose:
      - 3306
    env_file: ./identity_service/.env.docker
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    networks:
      - network-fmecg

networks:
  network-fmecg:
    driver: bridge
