FROM node:20-alpine AS node_builder

WORKDIR /web/

ENV PORT=3002
ENV WATCHPACK_POLLING=true

COPY package.json ./

RUN npm i -g npm@8

RUN npm i

# phải run npm install trước
COPY . .

CMD [ "npm", "run", "start" ]