@startuml


skinparam style strictuml

skinparam lifelineStrategy solid

skinparam ParticipantPadding 80

skinparam BoxPadding 10

autonumber

actor User as User

box "view" #LightGoldenRodYellow

participant UserInfoPage as UserInfoPage

end box

box "route" #lightBlue

participant UserRoute as UserRoute

end box


box "controller" #LightGoldenRodYellow
participant UserController as UserController

end box


box "model" #lightBlue
participant UserModel as UserModel

end box


User -> UserInfoPage: Request to change password
activate User
activate UserInfoPage

UserInfoPage -> UserRoute: GET api/users/{:userId}
activate UserRoute


UserRoute -> UserController: getUserProfile(req, res)
activate UserController

note right of UserRoute #Aqua
* Request param:
userId = req.body.userId
end note


UserController -> UserModel: findByPk(decodeToken.user_id)

activate  UserModel

UserModel --> UserController: return user

deactivate UserModel

opt user does not exist
  UserController --> UserRoute: return response error
end



UserController --> UserRoute: return response

deactivate UserController

UserRoute --> UserInfoPage: return response

deactivate UserRoute

UserInfoPage --> User: return response

deactivate UserInfoPage
deactivate User


@enduml


