' @startuml

' actor User
' boundary Controller
' database Database
' participant UserDB
' participant ResetTokenDB
' participant Nodemailer

' User -> Controller: POST /reset-password
' activate Controller

' Controller -> Controller: Validate input data
' alt Invalid data
'     Controller --> User: Error response
' else Valid data
'     Controller -> Database: Find user by email
'     activate Database
'     alt User not found
'         Database --> Controller: Null
'         Controller --> User: Error response
'     else User found
'         Database --> Controller: User data
'         deactivate Database

'         Controller -> ResetTokenDB: Create reset token
'         activate ResetTokenDB
'         ResetTokenDB --> Controller: Reset token data
'         deactivate ResetTokenDB

'         Controller -> Nodemailer: Send reset token email
'         activate Nodemailer
'         Nodemailer --> Controller: Email sent
'         deactivate Nodemailer

'         Controller --> User: Success response
'     end
' end

' @enduml



@startuml


skinparam style strictuml

skinparam lifelineStrategy solid

skinparam ParticipantPadding 70

skinparam BoxPadding 10

autonumber

actor User as User

box "view" #LightGoldenRodYellow

participant ResetPasswordPage as ResetPasswordPage

end box


box "route" #lightBlue

participant AuthRoute as AuthRoute

end box


box "controller" #LightGoldenRodYellow
participant AuthController as AuthController

end box


box "model" #lightBlue
participant UserModel as UserModel
participant ResetTokenModel as ResetTokenModel

end box


User -> ResetPasswordPage: Request to send reset password token
activate User
activate ResetPasswordPage

ResetPasswordPage -> AuthRoute: POST api/reset-password
activate AuthRoute

note right of ResetPasswordPage #Aqua
* Request param:
Content type: application/json
Request content:
- email: String
end note

AuthRoute -> AuthController: resetPasswordToken(req, res)
note right of AuthRoute #Aqua
* Request param:
{ email } = req.body
end note
activate AuthController

AuthController -> UserModel: findOne(param)
note right of AuthController #Aqua
  * Request param:
  email: String
end note

activate UserModel

UserModel --> AuthController: return user
deactivate UserModel
alt user existed
  AuthController -> AuthController: create reset token
  AuthController -> AuthController: create reset token expiration

  AuthController -> ResetTokenModel: create()
  note right of UserModel #Aqua
    * Request param:
     - user_id: user.user_id
     - token: resetToken
     - expiration: resetTokenExpiration
  end note

  activate ResetTokenModel
  ResetTokenModel --> AuthController: return
  deactivate ResetTokenModel

  AuthController -> AuthController: send reset token to user's email

  AuthController -> AuthRoute: return response
else user does not exist
AuthController -> AuthRoute: return response error
deactivate AuthController
end

AuthRoute --> ResetPasswordPage: return response
deactivate AuthRoute

ResetPasswordPage --> User: return response
deactivate ResetPasswordPage
deactivate User

@enduml
