@startuml

actor ":User" as User
boundary ":View Forgot password" as ClientApp
control ":Control Forgot password" as Control
entity ":Entity User" as Entity

activate User
User -> ClientApp: Click button forgot password
activate ClientApp
ClientApp -> ClientApp: Show forgot password view
ClientApp --> User
User -> ClientApp: Submit email to send verification code
ClientApp -> ClientApp: Validate format information
alt Format accepted
  ClientApp -> Control: Send information 
  activate Control
  Control -> Entity: Kiểm tra dữ liệu 
  ' keep fixing and asking MRTuan
  activate Entity
  Entity --> Control: Trả về kết quả kiểm tra
  deactivate Entity
  alt Kết quả hợp lệ
    Control --> ClientApp: Hiển thị đăng nhập thành công
    ClientApp --> User: Thông báo đăng nhập thành công
  else Kết quả không hợp lệ
    Control --> ClientApp: Hiển thị đăng nhập thất bại
    deactivate Control
    ClientApp --> User: Thông báo đăng nhập thất bại 
  end

else Định dạng đăng nhập không hợp lệ
  ClientApp -> User: Yêu cầu người dùng nhập lại
  deactivate ClientApp
end

skinparam style strictuml
@enduml
