@startuml

actor ":Người dùng" as User
boundary ":Giao diện quên mật khẩu" as ClientApp
control ":Control quên mật khẩu" as Control
entity ":Entity người dùng" as Entity

activate User
User -> ClientApp: Nhấn nút quên mật khẩu
activate ClientApp
ClientApp -> ClientApp: Hiển thị giao diện quên mật khẩu
ClientApp --> User
User -> ClientApp: Nhập thông tin để gửi mã xác nhận
ClientApp -> ClientApp: Kiểm tra định dạng thông tin
alt Định dạng đăng nhập hợp lệ
  ClientApp -> Control: Gửi thông tin 
  activate Control
  Control -> Entity: Kiểm tra dữ liệu
  activate Entity
  Entity --> Control: Trả về kết quả kiểm tra
  deactivate Entity
  alt Kết quả hợp lệ
    Control --> ClientApp: Hiển thị đăng nhập thành công
    ClientApp --> User: Thông báo đăng nhập thành công
  else Kết quả không hợp lệ
    Control --> ClientApp: Hiển thị đăng nhập thất bại
    deactivate Control
    ClientApp --> User: Thông báo đăng nhập thất bại 
  end

else Định dạng đăng nhập không hợp lệ
  ClientApp -> User: Yêu cầu người dùng nhập lại
end
@enduml
