@startuml

actor ":Người dùng" as User
boundary ":Giao diện nhắn tin" as ClientApp
control ":Control nhắn tin" as Control
entity ":Entity tin nhắn" as Entity

activate User
User -> ClientApp: Mở trang hội thoại
activate ClientApp
ClientApp -> ClientApp: Hiển thị giao diện hội thoại
ClientApp --> User
User -> ClientApp: Nhập nội dung tin nhắn

ClientApp -> Control: Gửi tin nhắn
activate Control
Control -> Entity: Lưu tin nhắn vào CSDL
activate Entity
Entity --> Control: Trả về dữ liệu
deactivate Entity
Control --> ClientApp: Trả về dữ liệu
deactivate Control
ClientApp --> User: Hiển thị tin nhắn người dùng gửi
deactivate ClientApp

@enduml
