@startuml

actor ":Người dùng" as User
boundary ":Giao diện lịch sử đo" as ClientApp
control ":Control lịch sử đo" as Control
entity ":Entity bản ghi" as Entity

activate User
User -> ClientApp: Nhấn nút chuyển sang trang lịch sử đo
activate ClientApp
ClientApp -> Control: Gửi yêu cầu lấy thông tin các bản ghi
activate Control
Control -> Entity: Truy vấn dữ liệu
activate Entity
Entity --> Control: Trả về kết quả
deactivate Entity
Control --> ClientApp: Hiển thị giao diện lịch sử bản ghi
deactivate Control

User -> ClientApp: Nhấn nút chọn xem một bản ghi
ClientApp -> Control: Gửi yêu cầu lấy thông tin chi tiết của bản ghi
activate Control
Control -> Entity: Truy vấn dữ liệu
activate Entity
Entity --> Control: Trả về kết quả
deactivate Entity
Control -> ClientApp: Hiển thị dữ liệu biểu đồ của bản ghi
deactivate Control
ClientApp --> User: Hiển thị biểu đồ cho người dùng
deactivate ClientApp

@enduml
