name: Automatic build and push images to Docker
on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - dockerfile: ./server-web/Dockerfile
            image: thaidmfinnick/fmecg-node-app
          - dockerfile: ./frontend_web/Dockerfile
            image: thaidmfinnick/fmecg-react-app
          - dockerfile: ./frontend_web/bin/Dockerfile
            image: thaidmfinnick/fmecg-bin-login
          - dockerfile: ./proxy/Dockerfile
            image: thaidmfinnick/fmecg-proxy

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}